sudo: false

language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_install:
  - echo 'Asia/Ho_Chi_Minh' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
  - mysql -u root -e 'SET GLOBAL time_zone="Asia/Ho_Chi_Minh";'
  - mysql -u root -e 'CREATE DATABASE test;'
  - psql -c 'CREATE DATABASE test;' -U postgres

after_script:

services:
  - mysql
  - postgresql
  
script:
  - mvn test -DskipTests=false -Dmysql.hostAndPort=localhost -Dmysql.user=root -Dmysql.pwd=""
  - mvn test -DskipTests=false -Dpgsql.hostAndPort=localhost -Dpgsql.user=postgres -Dpgsql.pwd=""
