sudo: false

language: java
jdk:
  - oraclejdk11

cache:
  directories:
  - $HOME/.m2

before_install:
  - echo 'Asia/Ho_Chi_Minh' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
  - mysql -u root -e 'CREATE DATABASE test;'

after_script:

services:
  - mysql
  
script:
  - mvn test -DskipTests=false -Dmysql.user=root -Dmysql.pwd="" 
