sudo: false

language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

before_install:
  - mysql -u root -e 'CREATE DATABASE test;'

after_script:

services:
  - mysql
  
script:
  - mvn test -Dmysql.user=root
